/*
 * This file is part of LiteEth.
 *
 * Copyright (c) 2026 Oliver Keller <oliver.keller@pm.me>
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * LiteX simulation module bridging a host TAP interface to RGMII pads.
 *
 * The module plays the external RGMII PHY: frames read from the TAP interface are sent to the
 * FPGA on rx_ctl/rx_data (DDR, with preamble/SFD and FCS) clocked by the RX clock, and frames
 * the FPGA transmits on tx_ctl/tx_data (sampled on both edges of its forwarded TX clock) are
 * checked (preamble, FCS) and written to the TAP interface. Between frames, the in-band status
 * reports a 1Gbps full-duplex link.
 *
 * The RX clock is generated by a LiteX "clocker" module; this module ticks after the design is
 * evaluated, so data changes on one RX clock edge take effect before the next one, as long as the
 * simulation timebase is shorter than half an RX clock period.
 *
 * Interfaces:
 * - "eth"        : rx_ctl, rx_data[3:0] (driven), tx_ctl, tx_data[3:0], tx_clk (sampled).
 * - other (clock): the RX clock signal, named after its interface.
 *
 * Arguments (JSON):
 * - "interface"  : TAP interface name (required).
 * - "ip"         : IPv4 address given to the TAP interface (optional).
 * - "mac"        : MAC address given to the TAP interface (optional, "xx:xx:xx:xx:xx:xx").
 *
 * Set RGMII_ETHERNET_DEBUG=1 in the environment to log frames on stderr.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>
#include "error.h"

#include <event2/listener.h>
#include <event2/util.h>
#include <event2/event.h>
#include <json-c/json.h>
#include <zlib.h>
#include "tapcfg.h"
#include "modules.h"

#define ETH_LEN         9018 /* Largest frame (without FCS). */
#define ETH_MIN_LEN       60 /* Smallest frame (without FCS). */
#define ETH_IFG           12 /* Inter-frame gap (bytes). */
#define RGMII_PREAMBLE     8 /* Preamble + SFD (bytes). */
#define RGMII_INBAND    0xdd /* In-band status: link up, 1Gbps, full-duplex (both nibbles). */

struct eth_packet_s {
  uint8_t data[ETH_LEN];
  size_t len;
  struct eth_packet_s *next;
};

struct session_s {
  /* Pads. */
  uint8_t *rx_clk;
  uint8_t *tx_clk;
  uint8_t *rx_ctl;
  uint8_t *rx_data;
  uint8_t *tx_ctl;
  uint8_t *tx_data;
  clk_edge_state_t rx_clk_edge;
  clk_edge_state_t tx_clk_edge;

  /* RX (TAP -> FPGA). */
  struct eth_packet_s *rx_head;
  struct eth_packet_s *rx_tail;
  uint8_t rx_buf[RGMII_PREAMBLE + ETH_LEN + 4];
  size_t rx_len;
  size_t rx_pos;
  int rx_ifg;
  uint8_t rx_byte;
  int rx_dv;

  /* TX (FPGA -> TAP). */
  uint8_t tx_buf[RGMII_PREAMBLE + ETH_LEN + 4];
  size_t tx_len;
  uint8_t tx_lo;
  int tx_lo_dv;
  int tx_dv;
  int tx_err;
  int tx_overflow;

  /* TAP. */
  tapcfg_t *tapcfg;
  int fd;
  struct event *ev;
  char *name;
};

static struct event_base *base = NULL;
static int debug = 0;

static void rgmii_log_frame(struct session_s *s, const char *dir, uint8_t *data, size_t len)
{
  size_t i;
  if(!debug)
    return;
  fprintf(stderr, "[rgmii_ethernet] %s %s %4zu bytes:", s->name, dir, len);
  for(i = 0; i < len && i < 16; i++)
    fprintf(stderr, " %02x", data[i]);
  fprintf(stderr, "\n");
}

/* Helpers ------------------------------------------------------------------------------------- */

static int rgmii_get_arg(char *args, char *arg, char **val, int required)
{
  int ret = RC_OK;
  json_object *jsobj = NULL;
  json_object *obj = NULL;

  *val = NULL;
  jsobj = json_tokener_parse(args);
  if(!jsobj || !json_object_is_type(jsobj, json_type_object)) {
    fprintf(stderr, "[rgmii_ethernet] invalid arguments: %s\n", args);
    ret = RC_JSERROR;
    goto out;
  }
  if(!json_object_object_get_ex(jsobj, arg, &obj)) {
    if(required) {
      fprintf(stderr, "[rgmii_ethernet] missing argument \"%s\" (%s)\n", arg, args);
      ret = RC_JSERROR;
    }
    goto out;
  }
  *val = strdup(json_object_get_string(obj));
out:
  if(jsobj)
    json_object_put(jsobj);
  return ret;
}

static void *rgmii_pad(struct pad_s *pads, char *name)
{
  int i;
  for(i = 0; pads[i].name; i++)
    if(!strcmp(pads[i].name, name))
      return pads[i].signal;
  return NULL;
}

/* RX: TAP -> FPGA ----------------------------------------------------------------------------- */

static void rgmii_tap_event(int fd, short event, void *arg)
{
  struct session_s *s = (struct session_s *)arg;
  struct eth_packet_s *p;
  int len;

  if(!(event & EV_READ))
    return;

  p = malloc(sizeof(struct eth_packet_s));
  if(!p)
    return;
  /* Read the TAP directly: tapcfg_read() goes through a 4096-byte buffer, truncating longer
   * frames (which would then get a valid FCS here). */
  len = read(s->fd, p->data, ETH_LEN);
  if(len <= 0) {
    free(p);
    return;
  }
  if(len < ETH_MIN_LEN) {
    memset(&p->data[len], 0, ETH_MIN_LEN - len);
    len = ETH_MIN_LEN;
  }
  p->len  = len;
  p->next = NULL;
  if(s->rx_tail)
    s->rx_tail->next = p;
  else
    s->rx_head = p;
  s->rx_tail = p;
}

static void rgmii_rx_load(struct session_s *s)
{
  struct eth_packet_s *p = s->rx_head;
  uint32_t crc;
  size_t i;

  s->rx_head = p->next;
  if(!s->rx_head)
    s->rx_tail = NULL;

  for(i = 0; i < RGMII_PREAMBLE - 1; i++)
    s->rx_buf[i] = 0x55;
  s->rx_buf[RGMII_PREAMBLE - 1] = 0xd5;
  memcpy(&s->rx_buf[RGMII_PREAMBLE], p->data, p->len);
  crc = crc32(0, p->data, p->len);
  for(i = 0; i < 4; i++)
    s->rx_buf[RGMII_PREAMBLE + p->len + i] = (crc >> (8*i)) & 0xff;
  s->rx_len = RGMII_PREAMBLE + p->len + 4;
  s->rx_pos = 0;
  rgmii_log_frame(s, "TAP->FPGA", p->data, p->len);
  free(p);
}

/* Falling RX clock edge: select the next byte and present its low nibble for the rising edge. */
static void rgmii_rx_next(struct session_s *s)
{
  if(!s->rx_len && !s->rx_ifg && s->rx_head)
    rgmii_rx_load(s);

  if(s->rx_len) {
    s->rx_dv   = 1;
    s->rx_byte = s->rx_buf[s->rx_pos++];
    if(s->rx_pos == s->rx_len) {
      s->rx_len = 0;
      s->rx_ifg = ETH_IFG;
    }
  } else {
    if(s->rx_ifg)
      s->rx_ifg--;
    s->rx_dv   = 0;
    s->rx_byte = RGMII_INBAND;
  }
  *s->rx_ctl  = s->rx_dv;
  *s->rx_data = s->rx_byte & 0xf;
}

/* Rising RX clock edge: present the high nibble (and RX_DV xor RX_ER) for the falling edge. */
static void rgmii_rx_high(struct session_s *s)
{
  *s->rx_ctl  = s->rx_dv;
  *s->rx_data = (s->rx_byte >> 4) & 0xf;
}

/* TX: FPGA -> TAP ----------------------------------------------------------------------------- */

static void rgmii_tx_frame(struct session_s *s)
{
  size_t sfd, len;
  uint32_t crc, fcs;
  uint8_t *frame;

  if(s->tx_err || s->tx_overflow) {
    fprintf(stderr, "[rgmii_ethernet] %s: TX frame dropped (%s)\n", s->name,
      s->tx_err ? "TX_ER" : "too long");
    return;
  }
  /* Preamble: 0x55... then SFD (0xd5). */
  for(sfd = 0; sfd < s->tx_len && s->tx_buf[sfd] == 0x55; sfd++);
  if(sfd == 0 || sfd >= s->tx_len || s->tx_buf[sfd] != 0xd5) {
    fprintf(stderr, "[rgmii_ethernet] %s: TX preamble/SFD error\n", s->name);
    return;
  }
  frame = &s->tx_buf[sfd + 1];
  len   = s->tx_len - sfd - 1;
  if(len < ETH_MIN_LEN + 4) {
    fprintf(stderr, "[rgmii_ethernet] %s: TX runt frame (%zu bytes)\n", s->name, len);
    return;
  }
  len -= 4;
  crc = crc32(0, frame, len);
  fcs = frame[len] | (frame[len + 1] << 8) | (frame[len + 2] << 16) | ((uint32_t)frame[len + 3] << 24);
  if(crc != fcs) {
    fprintf(stderr, "[rgmii_ethernet] %s: TX FCS error (expected %08x, got %08x)\n", s->name, crc, fcs);
    return;
  }
  rgmii_log_frame(s, "FPGA->TAP", frame, len);
  tapcfg_write(s->tapcfg, frame, len);
}

/* Rising TX clock edge: TX_EN and low nibble. */
static void rgmii_tx_low(struct session_s *s)
{
  s->tx_lo_dv = *s->tx_ctl & 1;
  s->tx_lo    = *s->tx_data & 0xf;
}

/* Falling TX clock edge: TX_EN xor TX_ER and high nibble complete the byte. */
static void rgmii_tx_high(struct session_s *s)
{
  int dv = s->tx_lo_dv;
  int er = dv ^ (*s->tx_ctl & 1);
  uint8_t byte = s->tx_lo | ((*s->tx_data & 0xf) << 4);

  if(dv) {
    if(!s->tx_dv) {
      s->tx_len      = 0;
      s->tx_err      = 0;
      s->tx_overflow = 0;
    }
    if(s->tx_len < sizeof(s->tx_buf))
      s->tx_buf[s->tx_len++] = byte;
    else
      s->tx_overflow = 1;
    s->tx_err |= er;
  } else if(s->tx_dv) {
    rgmii_tx_frame(s);
  }
  s->tx_dv = dv;
}

/* Module -------------------------------------------------------------------------------------- */

static int rgmii_ethernet_start(void *b)
{
  base  = (struct event_base *)b;
  debug = getenv("RGMII_ETHERNET_DEBUG") != NULL;
  printf("[rgmii_ethernet] loaded (%p)\n", base);
  return RC_OK;
}

static int rgmii_ethernet_new(void **sess, char *args)
{
  int ret = RC_OK;
  char *c_tap = NULL;
  char *c_ip  = NULL;
  char *c_mac = NULL;
  struct session_s *s = NULL;
  struct timeval tv = {10, 0};
  unsigned int m[6];
  char mac[6];
  int i;

  if(!sess) {
    ret = RC_INVARG;
    goto out;
  }
  s = (struct session_s *)malloc(sizeof(struct session_s));
  if(!s) {
    ret = RC_NOENMEM;
    goto out;
  }
  memset(s, 0, sizeof(struct session_s));

  if((ret = rgmii_get_arg(args, "interface", &c_tap, 1)) != RC_OK)
    goto out;
  if((ret = rgmii_get_arg(args, "ip", &c_ip, 0)) != RC_OK)
    goto out;
  if((ret = rgmii_get_arg(args, "mac", &c_mac, 0)) != RC_OK)
    goto out;

  s->name   = c_tap;
  s->rx_ifg = ETH_IFG;
  s->tapcfg = tapcfg_init();
  if(tapcfg_start(s->tapcfg, c_tap, 0) < 0) {
    fprintf(stderr, "[rgmii_ethernet] could not open TAP interface %s\n", c_tap);
    ret = RC_ERROR;
    goto out;
  }
  s->fd = tapcfg_get_fd(s->tapcfg);
  if(c_mac) {
    if(sscanf(c_mac, "%x:%x:%x:%x:%x:%x", &m[0], &m[1], &m[2], &m[3], &m[4], &m[5]) != 6) {
      fprintf(stderr, "[rgmii_ethernet] invalid MAC address: %s\n", c_mac);
      ret = RC_INVARG;
      goto out;
    }
    for(i = 0; i < 6; i++)
      mac[i] = m[i];
    tapcfg_iface_set_hwaddr(s->tapcfg, mac, 6);
  }
  if(c_ip)
    tapcfg_iface_set_ipv4(s->tapcfg, c_ip, 24);
  tapcfg_iface_set_status(s->tapcfg, TAPCFG_STATUS_ALL_UP);
  printf("[rgmii_ethernet] %s up\n", c_tap);

  s->ev = event_new(base, s->fd, EV_READ | EV_PERSIST, rgmii_tap_event, s);
  event_add(s->ev, &tv);

out:
  free(c_ip);
  free(c_mac);
  *sess = (void *)s;
  return ret;
}

static int rgmii_ethernet_add_pads(void *sess, struct pad_list_s *plist)
{
  struct session_s *s = (struct session_s *)sess;
  struct pad_s *pads;

  if(!sess || !plist)
    return RC_INVARG;
  pads = plist->pads;
  if(!strcmp(plist->name, "eth")) {
    s->rx_ctl  = rgmii_pad(pads, "rx_ctl");
    s->rx_data = rgmii_pad(pads, "rx_data");
    s->tx_ctl  = rgmii_pad(pads, "tx_ctl");
    s->tx_data = rgmii_pad(pads, "tx_data");
    s->tx_clk  = rgmii_pad(pads, "tx_clk");
  } else {
    s->rx_clk  = rgmii_pad(pads, plist->name);
  }
  return RC_OK;
}

static int rgmii_ethernet_tick(void *sess, uint64_t time_ps)
{
  struct session_s *s = (struct session_s *)sess;
  clk_edge_t edge;

  if(!s->rx_clk || !s->rx_ctl || !s->rx_data || !s->tx_ctl || !s->tx_data)
    return RC_ERROR;

  /* TX, sampled on the forwarded TX clock (or the RX clock when not exposed). */
  edge = clk_edge(&s->tx_clk_edge, s->tx_clk ? *s->tx_clk : *s->rx_clk);
  if(edge == CLK_EDGE_RISING)
    rgmii_tx_low(s);
  else if(edge == CLK_EDGE_FALLING)
    rgmii_tx_high(s);

  /* RX. */
  edge = clk_edge(&s->rx_clk_edge, *s->rx_clk);
  if(edge == CLK_EDGE_RISING)
    rgmii_rx_high(s);
  else if(edge == CLK_EDGE_FALLING)
    rgmii_rx_next(s);

  return RC_OK;
}

static struct ext_module_s ext_mod = {
  "rgmii_ethernet",
  rgmii_ethernet_start,
  rgmii_ethernet_new,
  rgmii_ethernet_add_pads,
  NULL,
  rgmii_ethernet_tick
};

int litex_sim_ext_module_init(int (*register_module)(struct ext_module_s *))
{
  /* Build zlib's CRC table up front. */
  get_crc_table();
  return register_module(&ext_mod);
}
